l = {'a': [ 'air conditioner', 'air cooler',  'almond', 'anaconda', 'animal', 'animals', 'ant', 'ape', 'apple', 'armor', 'arrow','atm', 'air bag', 'arm', ' angel', 'airplane', 'aquarium'] ,
'b': ['baboon', 'baby', 'badminton', 'bake',  'ball', 'banana', 'banyan','bag', 'baseball', 'basement', 'basketball', 'bat', 'bathroom', 'battlefield', 'bear', 'bedroom', 'bee', 'bicycle', 'bike', 'billiards', 'bird', 'blackboard', 'book', 'bookshelf', 'boot',	'bottle',  'boy', 'bread', 'breakfast', 'bride', 'bridge', 'bronze medal', 'broom', 'buffalo',  'building', 'bull', 'buns', 'bus',  'butter', 'butterfly', ],
'c': ['cable','cake', 'calculator','comb' 'calender', 'camel', 'clothes','candy', 'canteen', 'car', 'carpet', 'carrot', 'cashew',  'cat', 'caterpillar', 'cattle', 'ceiling', 'chair', 'chalk', 'champion', 'cheese', 'cheetah', 'cherry', 'chicken', 'child', 'children', 'chili', 'chips', 'chocolate', 'classroom', 'clothes', 'cloud', 'clouds', 'cobra', 'coconut', 'coffee','computer', 'cook', 'cookie', 'cop', 'corn',  'cow', 'cream','crocodile', 'crow', 'cucumber', 'cupcake', 'curry',  'cycle',  'cyclone'],
'd': ['dairy',  'deer', 'dentist',  'dessert', 'diamond', 'dinosaur', 'dog', 'dolphin', 'donkey', 'door', 'door bell', 'doughnut', 'dove', 'dragonfly', 'drain',  'duck', 'dustbin'],
'e': ['eagle', 'eel', 'egg', 'elephant',  'entryway', 'eraser'],
'f': ['foot','footwear', 'factory', 'fan', 'feast', 'fence', 'field', 'finch', 'fish', 'floor', 'flour', 'fly', 'fog', 'food', 'football', 'forest', 'fort', 'fossil', 'fox', 'french fries', 'frog', 'fruit', 'furniture', 'flower', 'flight', 'floor'],
'g': ['game', 'garage', 'garden',  'gate', 'giraffe', 'glasses', 'globe', 'goal', 'goat', 'gold', 'gold medal','glass', 'golf',  'goose', 'gorilla', 'grain', 'grape', 'grasshopper', 'groom', 'group', 'guard',  'gun', 'gutter', 'gym'],
'h': [ 'hall', 'heater', 'helmet', 'hen', 'hippo', 'hockey', 'home', 'horse', 'hot dog', 'house', 'human', 'hummingbird',],
'i': ['ice', 'ice cream', 'infant', 'ink', 'insects'],
'j': ['jaguar',  'jam', 'jeep', 'jelly', 'jellybeans', 'jellyfish', 'jug', 'juice', 'jungle'],
'k': ['kangaroo', 'key', 'keyboard', 'kitchen', 'kite', 'kiwi', 'knife', "kennel", "knot"],
'l': ['ladder', 'lake', 'lamp', 'laptop', 'lemon', 'leopard', 'lion', 'living room', 'lizard', 'lock', 'loft', 'lollipop',  'lunch box'],
'm': ['mailbox','mango', 'map', 'market', 'mat','milk', 'medal', 'men', 'metal', 'mice', 'mirror', 'mo+bile', 'mobilephone', 'mobile phone', 'mongoose', 'monitor', 'monkey', 'mosquito', 'motherboard', 'mouse', 'mousepad', 'muffin'],
'n': [ 'nest', 'newspaper', 'notebook',],
'o': ['oak',  'oil', 'onion', 'orange', 'owl', 'ox'],
'p': ['paddle', 'painting', 'pan', 'panda', 'pantry', 'paper','pant', 'paperweight', 'parachute', 'parrot', 'pasta', 'peacock', 'peanut', 'pen', 'pencil', 'penguin', 'pepper', 'person',  'pickle', 'picnic', 'picture', 'pig', 'pigeon', 'pilot', 'pineapple', 'pizza', 'plane', 'plant', 'plumber', 'police', 'polo', 'pool', 'popcorn', 'potato', 'protein', 'pumpkin', 'purse', 'python'],
'q': [],
'r': ['rabbit','racket', 'racquet', 'radio', 'rafting', 'railway station', 'rain', 'rain forest', 'rainbow', 'rat', 'river', 'road', 'rock', 'rod', 'roller', 'roof', 'room', 'rugby', 'ruler'],
's': ['sole', 'sandal', 'salad', 'salt', 'sandstorm', 'sandwich', 'satellite','shirt', 'sausage', 'school bus', 'school boy', 'school girl',  'scissors', 'scoreboard', 'scorpion', 'sea', 'seal', 'seeds','shark', 'sheep', 'shelf','shock', 'shocks', 'shoe', 'shoes', 'shop', 'silver', 'silver medal',  'skate', 'skates', 'ski',  'sky', 'slipper', 'slippers', 'snack', 'snail', 'snow', 'snowboard', 'snowfall', 'snowstorm', 'soccer',  'sparrow', 'spectacles', 'spices', 'spoon', 'spork', 'sport',  'spring', 'sprouts', 'squirrel', 'stadium', 'staff', 'stairs', 'starfish', 'station', 'strawberry', 'student', 'sugar', 'sunflower', 'sunrise', 'sunset', 'swan', 'swimming pool', 'switch'],
't': ['table', 'table tennis', 'tadpole', 'tea', 'teapot',  'telephone', 'tennis', 'thunderstorm', 'tiger', 'toffee', 'toilet', 'tomato', 'tornado', 'tortoise', 'track', 'train', 'tree', 'turkey', 'turmeric', 'turtle', 'typewriter', 'typhoon',],
'u': [ 'uniform', 'utensils'],
'v': ['vacuum cleaner', 'vapor', 'vegetable', 'vehicle', 'volley ball', 'vulture'],
'w': ['wafer',  'wall clock', 'washing machine', 'watch', 'water', 'watermelon', 'wave', 'weapon', 'whale', 'wheat', 'whiteboard', 'wicket', 'window',  'wire', 'wolf', 'wolverine', 'women', 'woodchuck',  'wrist watch',],
'x': [],
'y': ['yak', 'yard', 'yogurt'],
'z': ['zebra']}